# Compare total amount of time the rats in each group spent eating and drinking sucrose (consuming calories)

This Jupyter notebook performs **Student's T-Test** on the **total** calorie-consuming activity of the 4 groups of rats and plots the day vs night calorie-consumign activity of the *Ad Lib* rats

## Import Libraries

In [1]:
#----------------------------------------------------------
# Import important libraries
#----------------------------------------------------------
import pandas as pd
import numpy as np
import datetime
import os 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

### Download data on total amount of time spent eating and drinking sucrose

The variables "light_food" and "dark_food" contain total time(in seconds) each rat spent eating during light and dark period respectively

* Dark Period: before 9:00
* Light Period: after 9:00

In [2]:
# Read in CSV file with "light_food" and "dark_food" data
feeding_location = 'https://www.dropbox.com/s/d631mi6z7c9g9lt/food_total.csv?dl=1'
feeding_data = pd.read_csv(feeding_location , index_col=0)

# Combine number of seconds in dark and light periods together into new column called "total_food"
feeding_data['total_food'] = feeding_data['light_food'] + feeding_data['dark_food']
feeding_data

    light_food  dark_food                group  total_food
2         2119       5022       control ad lib        7141
3         1071       3318       control ad lib        4389
4         2600       3987       control ad lib        6587
5          591       2145       control ad lib        2736
6         1812       3949       control ad lib        5761
7         2391       4661       control ad lib        7052
8         1199       3383       control ad lib        4582
9         1099       2676       control ad lib        3775
10           0       1524  control restriction        1524
11           0        502  control restriction         502
12           0       2075  control restriction        2075
13           0       2129  control restriction        2129
14           0       2810  control restriction        2810
15           0       1474  control restriction        1474
16           0       2209  control restriction        2209
17           0       5736  control restriction        5736
18           0       1139  control restriction        1139
21         144       2626          HFHS ad lib        2770
22         456       2776          HFHS ad lib        3232
23         420       2873          HFHS ad lib        3293
26         388        778          HFHS ad lib        1166
27          76       1357          HFHS ad lib        1433
29           0       2282     HFHS restriction        2282
30           0       1612     HFHS restriction        1612
31           0       1822     HFHS restriction        1822
32           0        840     HFHS restriction         840
33           0        914     HFHS restriction         914
35           0       2562     HFHS restriction        2562
36           0       1708     HFHS restriction        1708

In [3]:
# Read in CSV file with "light_food" and "dark_food" data
sucrose_location = 'https://www.dropbox.com/s/109v6g9d9le45xk/sucrose_total.csv?dl=1'
sucrose_data = pd.read_csv(sucrose_location , index_col=0)

# Combine number of seconds in dark and light periods together into new column called "total_food"
sucrose_data['total_sucrose'] = sucrose_data['light_sucrose'] + sucrose_data['dark_sucrose']
sucrose_data

    light_sucrose  dark_sucrose             group  total_sucrose
21            358           903       HFHS ad lib           1261
22            266           529       HFHS ad lib            795
23             83           545       HFHS ad lib            628
26            460           722       HFHS ad lib           1182
27            183           642       HFHS ad lib            825
29              0           468  HFHS restriction            468
30              0           420  HFHS restriction            420
31              0           824  HFHS restriction            824
32              0           731  HFHS restriction            731
33              0           489  HFHS restriction            489
35              0           833  HFHS restriction            833
36              0           472  HFHS restriction            472

## Create dataframe with total amount of time spent drinking sucrose AND feeding

The variables "light" and "dark" contain total time(in seconds) each rat spent drinking sucrose AND feeding during light and dark period respectively

* Dark Period: before 9:00
* Light Period: after 9:00

In [4]:
sucrose_and_feeding_data = feeding_data.drop(["group"], axis = 1).rename(columns={"light_food": "light", "dark_food": "dark", "total_food": "total"})
sucrose_and_feeding_data = sucrose_and_feeding_data.add(sucrose_data.drop(["group"], axis = 1).rename(columns={"light_sucrose": "light", "dark_sucrose": "dark", "total_sucrose": "total"}), fill_value = 0)
sucrose_and_feeding_data = sucrose_and_feeding_data.astype(int)
sucrose_and_feeding_data["group"] = feeding_data["group"]
sucrose_and_feeding_data

    light  dark  total                group
2    2119  5022   7141       control ad lib
3    1071  3318   4389       control ad lib
4    2600  3987   6587       control ad lib
5     591  2145   2736       control ad lib
6    1812  3949   5761       control ad lib
7    2391  4661   7052       control ad lib
8    1199  3383   4582       control ad lib
9    1099  2676   3775       control ad lib
10      0  1524   1524  control restriction
11      0   502    502  control restriction
12      0  2075   2075  control restriction
13      0  2129   2129  control restriction
14      0  2810   2810  control restriction
15      0  1474   1474  control restriction
16      0  2209   2209  control restriction
17      0  5736   5736  control restriction
18      0  1139   1139  control restriction
21    502  3529   4031          HFHS ad lib
22    722  3305   4027          HFHS ad lib
23    503  3418   3921          HFHS ad lib
26    848  1500   2348          HFHS ad lib
27    259  1999   2258          HFHS ad lib
29      0  2750   2750     HFHS restriction
30      0  2032   2032     HFHS restriction
31      0  2646   2646     HFHS restriction
32      0  1571   1571     HFHS restriction
33      0  1403   1403     HFHS restriction
35      0  3395   3395     HFHS restriction
36      0  2180   2180     HFHS restriction

## Perform T-Tests for:
1. Comparisons among diet groups for Total Calorie Consumption
2. Comparisons among diet groups for Day vs Night Calorie Consumption

In [16]:
df = pd.DataFrame(columns = ["group1", "group2", "t-statistic", "p-value"])

# T-Test #1: Control Ad Lib vs Control Restriction Total Calorie Consumption
t, p = stats.ttest_ind(sucrose_and_feeding_data["total"].where(sucrose_and_feeding_data.group == "control ad lib").dropna(), 
                      sucrose_and_feeding_data["total"].where(sucrose_and_feeding_data.group == "control restriction").dropna())
df.loc[0] = ["control ad lib", "control restriction", t, p]
# T-Test #2: HFHS Ad Lib vs HFHS Restriction Total Calorie Consumption
t, p = stats.ttest_ind(sucrose_and_feeding_data["total"].where(sucrose_and_feeding_data.group == "HFHS ad lib").dropna(), 
                      sucrose_and_feeding_data["total"].where(sucrose_and_feeding_data.group == "HFHS restriction").dropna())
df.loc[1] = ["HFHS ad lib", "HFHS restriction", t, p]
# T-Test #3: Control Ad Lib Day vs Night Calorie Consumption
t, p = stats.ttest_ind(sucrose_and_feeding_data["light"].where(sucrose_and_feeding_data.group == "control ad lib").dropna(), 
                      sucrose_and_feeding_data["dark"].where(sucrose_and_feeding_data.group == "control ad lib").dropna())
df.loc[2] = ["Control ad lib Day", "Control ad lib Night", t, p]
# T-Test #4: HFHS Ad Lib vs HFHS Restriction Total Calorie Consumption
t, p = stats.ttest_ind(sucrose_and_feeding_data["light"].where(sucrose_and_feeding_data.group == "HFHS ad lib").dropna(), 
                      sucrose_and_feeding_data["dark"].where(sucrose_and_feeding_data.group == "HFHS ad lib").dropna())
df.loc[3] = ["HFHS ad lib Day", "HFHS ad lib Night", t, p]

In [18]:
df.to_csv("Total_and_Day_vs_Night_Calorie_Consumption_T_Tests.csv")
df

               group1                group2  t-statistic   p-value
0      control ad lib   control restriction     4.060603  0.001025
1         HFHS ad lib      HFHS restriction     2.211955  0.051390
2  Control ad lib Day  Control ad lib Night    -4.773543  0.000297
3     HFHS ad lib Day     HFHS ad lib Night    -5.080587  0.000952