# Behavioral Research: Does sugar and fat change the sucrose drinking behavior of animals?

This Jupyter notebook performs statistical analysis on each restricted experimental group's **hourly** sucrose drinking activities against the first hour

## Import Libraries and Excel Sheets

In [2]:
#----------------------------------------------------------
# Import important libraries
#----------------------------------------------------------
import pandas as pd
import numpy as np
import datetime
import os 
from scipy import stats
import math

## Download Hourly Sucrose Activity

In [3]:
# Read in CSV file with hourly data
sucrose_hourly_location = "https://www.dropbox.com/s/vsg8flaw5xe7bf1/sucrose_total_by_hour.csv?dl=1"
sucrose_hourly_data = pd.read_csv(sucrose_hourly_location, index_col = 0)

metafile = sucrose_hourly_data.group
sucrose_hourly_data.drop(["group"], axis = 1, inplace=True) 
sucrose_hourly_data

,21:00,22:00,23:00,0:00,1:00,2:00,3:00,4:00,5:00,6:00,...,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,19:00,20:00
21,75.0,121.0,102.0,0.0,129.0,78.0,86.0,0.0,0.0,123.0,...,167.0,104.0,0.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0
22,93.0,31.0,18.0,0.0,156.0,0.0,111.0,47.0,73.0,0.0,...,99.0,0.0,0.0,0.0,0.0,0.0,0.0,167.0,0.0,0.0
23,30.0,75.0,63.0,47.0,70.0,0.0,0.0,100.0,0.0,0.0,...,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0
26,52.0,112.0,37.0,0.0,28.0,220.0,0.0,0.0,89.0,103.0,...,0.0,228.0,0.0,59.0,0.0,0.0,0.0,77.0,0.0,0.0
27,160.0,0.0,33.0,0.0,182.0,127.0,0.0,0.0,0.0,140.0,...,0.0,0.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
29,0.0,0.0,191.0,0.0,45.0,76.0,50.0,0.0,6.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,32.0,32.0,0.0,49.0,0.0,103.0,126.0,78.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0.0,0.0,6.0,36.0,153.0,73.0,58.0,241.0,0.0,257.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,0.0,0.0,151.0,33.0,157.0,0.0,233.0,0.0,120.0,37.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,187.0,71.0,23.0,68.0,0.0,4.0,0.0,136.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,0.0,0.0,359.0,15.0,0.0,115.0,0.0,96.0,86.0,162.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,0.0,0.0,175.0,0.0,69.0,0.0,0.0,198.0,30.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Running T-Tests to Compare All Hours Against the First Hour of Binge-Eating

In [6]:
df = pd.DataFrame(columns = ["diet", "group1", "group2", "t-statistic", "p-value"])
diet_groups = ["HFHS restriction"]
i = 0
for group in diet_groups:
    ids = metafile[metafile == group].index
    for hour in sucrose_hourly_data:
        sucrose_series = sucrose_hourly_data.loc[ids]
        if sucrose_series[hour].isnull().all():
            t = "None"
            p = "None"
        else:
            t, p = stats.ttest_ind(sucrose_series["23:00"].dropna(), 
                          sucrose_series[hour].dropna())
        df.loc[i] = [group, "23:00", hour, t, p]
        i += 1

In [7]:
df.to_csv("Restricted_Animals_First_Hour_Excessive_Sucrose_Drinking_T_Tests.csv")
df

                diet group1 group2  t-statistic   p-value
0   HFHS restriction  23:00  21:00     3.567369  0.003871
1   HFHS restriction  23:00  22:00     3.567369  0.003871
2   HFHS restriction  23:00  23:00     0.000000  1.000000
3   HFHS restriction  23:00   0:00     2.896910  0.013403
4   HFHS restriction  23:00   1:00     1.838404  0.090870
5   HFHS restriction  23:00   2:00     2.194547  0.048610
6   HFHS restriction  23:00   3:00     1.988661  0.070033
7   HFHS restriction  23:00   4:00     1.136173  0.278066
8   HFHS restriction  23:00   5:00     2.136336  0.053942
9   HFHS restriction  23:00   6:00     0.866112  0.403413
10  HFHS restriction  23:00   7:00     3.567369  0.003871
11  HFHS restriction  23:00   8:00     3.567369  0.003871
12  HFHS restriction  23:00   9:00     3.567369  0.003871
13  HFHS restriction  23:00  10:00     3.567369  0.003871
14  HFHS restriction  23:00  11:00     3.567369  0.003871
15  HFHS restriction  23:00  12:00     3.567369  0.003871
16  HFHS restriction  23:00  13:00     3.567369  0.003871
17  HFHS restriction  23:00  14:00     3.567369  0.003871
18  HFHS restriction  23:00  15:00     3.567369  0.003871
19  HFHS restriction  23:00  16:00     3.567369  0.003871
20  HFHS restriction  23:00  17:00     3.567369  0.003871
21  HFHS restriction  23:00  18:00     3.567369  0.003871
22  HFHS restriction  23:00  19:00     3.567369  0.003871
23  HFHS restriction  23:00  20:00     3.567369  0.003871